### ISSUE TITLE
Question: Old script renamed to DriveMappping.ps1

### ISSUE THREAD

**Issue by Schnabulation** [nicolonsky/IntuneDriveMapping#39]
Hi there...

This is a quick question: I have replaced the script DriveMapping.ps1 with a new version in InTune. The new script gets deployed perfectly fine but I have noticed that the already existing script on the endpoints gets renamed to DriveMappping.ps1 (with three "p" in the name).

This is not an issue with the script or its feature-set it's just that I could not find a function in the script that would be responsible for this renaming. Is this intended?

**Comment by nicolonsky** [comment]
The old generated scripts had a typo and contained three 'p' characters in the name.
Newly genarated scripts do not have the typo present.

https://github.com/nicolonsky/IntuneDriveMapping/blob/687cbc35b6b65d26546ade3f2268947ac6aaf098/IntuneDriveMapping/wwwroot/bin/IntuneDriveMappingTemplate.ps1#L260

________________________________
From: Steve Heller ***@***.***>
Sent: Wednesday, May 4, 2022 2:23:42 PM
To: nicolonsky/IntuneDriveMapping ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nicolonsky/IntuneDriveMapping] Question: Old script renamed to DriveMappping.ps1 (Issue #39)


Hi there...

This is a quick question: I have replaced the script DriveMapping.ps1 with a new version in InTune. The new script gets deployed perfectly fine but I have noticed that the already existing script on the endpoints gets renamed to DriveMappping.ps1 (with three "p" in the name).

This is not an issue with the script or its feature-set it's just that I could not find a function in the script that would be responsible for this renaming. Is this intended?

**Comment by Phenix51** [comment]
I had added a small section to my drivemapping script to removal of the old scheduled tasks when I had updated this prior to the old generated script being updated.

 `$taskname = "IntuneDriveMapping","InTuneDriveMapping"

foreach ($task in $taskname)
{
$taskExists = Get-ScheduledTask | Where-Object {$_.TaskName -like $task }
	If ($taskExists)
	{	#Removes the Scheduled Task in queue
		Unregister-ScheduledTask -TaskName $task -Confirm:$false
		Write-Host "The Scheduled Task $task has been removed."
	} else 
	{
		Write-Host "The Scheduled Task $task did not exist."
	}`

I wasn't concerned about the initial script since it wasn't being called by a scheduledtask any longer, but you could certainly have it built into your version of the script to search and remove the old DriveMappping.ps1 file if it exists on your user's PC.

**Comment by Schnabulation** [comment]
Ah I see - this makes sense, thank you!
